server:
  port: 9000

scanPackages:
  - com.lee.server.controller
  - com.lee.server.service
  - com.lee.server.repository
  - com.lee.server.conf
  - com.lee.server.exception

demo:
  conf:
    name: hello